import { NextRequest, NextResponse } from 'next/server'
import crypto from 'crypto'
import { createServiceRoleClient } from '@/lib/supabase/server'

// =============================================================================
// Route handler: POST /api/payments/callback
// =============================================================================
//
// Razorpay redirects here with a POST request after a payment is completed
// when `callback_url` is used (which is best practice for mobile / UPI intent flows).
//
// The payload is URL-encoded form data containing:
// - razorpay_payment_id
// - razorpay_order_id
// - razorpay_signature

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData()
    const razorpay_payment_id = formData.get('razorpay_payment_id') as string | null
    const razorpay_order_id = formData.get('razorpay_order_id') as string | null
    const razorpay_signature = formData.get('razorpay_signature') as string | null
    
    // Also captures error states if the payment failed
    const error_code = formData.get('error[code]') as string | null

    // ── 1. If there's an explicit error from Razorpay, redirect to a failed state
    if (error_code) {
      // Razorpay passes `error[metadata]` which contains order_id. We could parse it,
      // but typically we can just redirect them back to the payment page.
      // We'll redirect to the homepage or orders page if we can't extract the order ID.
      let platformOrderId = ''
      try {
        const metadataStr = formData.get('error[metadata]') as string
        if (metadataStr) {
          const metadata = JSON.parse(metadataStr)
          // we need our internal platform order ID. Wait, Razorpay's metadata usually 
          // contains razorpay_order_id. We'd have to look it up.
          // For simplicity, just redirect to the home page or a generic error page.
        }
      } catch (e) {
        // ignore
      }
      return NextResponse.redirect(new URL('/?error=payment_failed', req.url), 303)
    }

    if (!razorpay_payment_id || !razorpay_order_id || !razorpay_signature) {
      console.error('[callback] Missing required razorpay parameters')
      return NextResponse.redirect(new URL('/?error=missing_payment_info', req.url), 303)
    }

    // ── 2. Fetch the restaurant's razorpay_key_secret ──────────────────────
    const supabase = await createServiceRoleClient()
    
    const { data: orderData, error: orderError } = await supabase
      .from('orders')
      .select('id, restaurant:restaurants(razorpay_key_secret)')
      .eq('razorpay_order_id', razorpay_order_id)
      .single()

    if (orderError || !orderData) {
      console.error(`[callback] Could not find order for razorpay_order_id: ${razorpay_order_id}`)
      return NextResponse.redirect(new URL('/?error=order_not_found', req.url), 303)
    }

    const restaurant = Array.isArray(orderData.restaurant) ? orderData.restaurant[0] : orderData.restaurant
    const keySecret = restaurant?.razorpay_key_secret

    if (!keySecret) {
      console.error('[callback] Restaurant does not have a razorpay_key_secret configured')
      return NextResponse.redirect(new URL('/?error=configuration_error', req.url), 303)
    }

    // ── 3. Verify HMAC-SHA256 signature ──────────────────────────────────────
    // Signature is generated by concatenating order_id and payment_id with a pipe
    const body = `${razorpay_order_id}|${razorpay_payment_id}`
    
    const expectedSignature = crypto
      .createHmac('sha256', keySecret)
      .update(body)
      .digest('hex')

    const isValid = expectedSignature === razorpay_signature

    if (!isValid) {
      console.warn('[callback] Invalid signature — request rejected')
      return NextResponse.redirect(new URL(`/?error=invalid_signature`, req.url), 303)
    }

    // ── 4. Update the order in the database ──────────────────────────────────
    // The webhook might have already done this, but we do it here too just in case
    // to ensure the user sees the success state immediately.
    const { error: updateError } = await supabase
      .from('orders')
      .update({
        payment_status: 'paid',
        payment_id: razorpay_payment_id,
        status: 'confirmed',
      })
      .eq('id', orderData.id)

    if (updateError) {
      console.error('[callback] Failed to update order status:', updateError.message)
      // Even if update fails, payment was verified. Webhook will likely catch it.
    }

    // ── 5. Redirect to the order confirmation page ───────────────────────────
    return NextResponse.redirect(new URL(`/order-confirmed/${orderData.id}`, req.url), 303)

  } catch (err) {
    console.error('[callback] Unexpected error:', err)
    return NextResponse.redirect(new URL('/?error=unexpected_error', req.url), 303)
  }
}
